/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#fe7935",
        "surface-tint": "#335ca9",
        "primary-container": "#1c4a96",
        "surface-container": "#eeeef0",
        "on-tertiary-container": "#ffa6a4",
        "surface-variant": "#e2e2e5",
        "error-container": "#ffdad6",
        "on-primary-container": "#a1bdff",
        "on-secondary-container": "#6d2b00",
        "secondary-container": "#fe7935",
        "on-tertiary-fixed": "#410007",
        "inverse-on-surface": "#f0f0f3",
        "on-primary-fixed": "#001a43",
        "on-primary-fixed-variant": "#124490",
        "primary-fixed-dim": "#aec6ff",
        "on-error": "#ffffff",
        outline: "#737782",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#ffb692",
        "tertiary-container": "#9e001f",
        "secondary-fixed": "#ffdbcb",
        "ocean-blue": "#2E6FD9",
        background: "#f9f9fc",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#ffb3b1",
        surface: "#f9f9fc",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#92001c",
        "on-secondary-fixed": "#341100",
        "on-tertiary": "#ffffff",
        "border-muted": "#E2E8F0",
        "surface-container-highest": "#e2e2e5",
        "surface-alt": "#F8FAFC",
        "on-primary": "#ffffff",
        "surface-dim": "#dadadc",
        "surface-bright": "#f9f9fc",
        "tertiary-fixed": "#ffdad8",
        "surface-container-high": "#e8e8ea",
        "outline-variant": "#c3c6d3",
        "on-surface": "#1a1c1e",
        "on-secondary": "#ffffff",
        tertiary: "#730014",
        "on-background": "#1a1c1e",
        "on-surface-variant": "#434751",
        "surface-container-low": "#f3f3f6",
        "surface-container-lowest": "#ffffff",
        primary: "#003376",
        "inverse-surface": "#2f3133",
        "on-secondary-fixed-variant": "#e8641f",
        "inverse-primary": "#aec6ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        gutter: "24px",
        "section-padding": "120px",
        "margin-desktop": "64px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "display-lg": ['"Source Serif 4"'],
        "display-lg-mobile": ['"Source Serif 4"'],
        "headline-sm": ['"Source Serif 4"'],
        "headline-md": ['"Source Serif 4"'],
        "body-lg": ["Manrope"],
        "label-md": ["Manrope"],
        caption: ["Manrope"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
};
